### ISSUE TITLE
Recording different objects in arcore

### ISSUE THREAD

**Issue by samuelprince77** [spaceLenny/recordablesurfaceview#11]
I am able to record the entire surface view of the helloAR project. I would like to record two videos simultaneously, the background renderer and the entire rendering with the 3d object placed over the background renderer(camera feed). Essentially saving the camera feed to one video and the camera+AR feed to another video. Currently i am taking snapshots of every frame but this is way too slow and skips a bunch of frames. Is there a way i can implement this with this library?

**Comment by spaceLenny** [comment]
I can see a way for you to record one or the other fairly easily. onDrawFrame is called twice in here: once for the screen, then once for the media surface.

It could be fairly straightforward to draw both to the screen and then on the second pass (the pass where it draws to the media surface) only draw the AR components.

A hard problem, however is that a media recorder can only bind to one surface at a time, so in order to do both you'd have to add another surface and media recorders to the GL stack and another render pass.

**Comment by samuelprince77** [comment]
Thanks for you reply.
> It could be fairly straightforward to draw both to the screen and then on the second pass (the pass where it draws to the media surface) only draw the AR components.
I am having some trouble getting that to work. I get the concept and here is how i am implementing it:
In MyGLRenderer.java - i draw both to the screen 
In MyGLSurfaceView.java - i only draw the square.(draws to media surface?)
This results in the screen only displaying the square and also only recording the square. I would like to draw both the square and the triangle to the screen (display) but only save a video containing the square without the triangle. Is there something i am missing in my process?

**Comment by samuelprince77** [comment]
Found the solution! i was looking at this all wrong, i added a method to the RenderCallbacks interfaces that would be called during the recording instead of onDrawFrame. This method would draw only the square hence achieving the recording of only one element(square). Thanks again!

**Comment by Noltibus** [comment]
@samuelprince77 would you share your project with me? I`m struggeling to get RecordableSurfaceView to work with ArCore in my existing app and an example would certaintly help!

**Comment by spaceLenny** [comment]
closing as it seems to be resolved
